// Code generated by smithy-go-codegen DO NOT EDIT.

package types

type CertificateField string

// Enum values for CertificateField
const (
	CertificateFieldX509Subject CertificateField = "x509Subject"
	CertificateFieldX509Issuer  CertificateField = "x509Issuer"
	CertificateFieldX509SAN     CertificateField = "x509SAN"
)

// Values returns all known values for CertificateField. Note that this can be
// expanded in the future, and so it is only as up to date as the client.
//
// The ordering of this slice is not guaranteed to be stable across updates.
func (CertificateField) Values() []CertificateField {
	return []CertificateField{
		"x509Subject",
		"x509Issuer",
		"x509SAN",
	}
}

type DeletionStatus string

// Enum values for DeletionStatus
const (
	DeletionStatusSucceeded DeletionStatus = "SUCCEEDED"
	DeletionStatusFailed    DeletionStatus = "FAILED"
)

// Values returns all known values for DeletionStatus. Note that this can be
// expanded in the future, and so it is only as up to date as the client.
//
// The ordering of this slice is not guaranteed to be stable across updates.
func (DeletionStatus) Values() []DeletionStatus {
	return []DeletionStatus{
		"SUCCEEDED",
		"FAILED",
	}
}

type NotificationChannel string

// Enum values for NotificationChannel
const (
	NotificationChannelAll         NotificationChannel = "ALL"
	NotificationChannelCloudWatch  NotificationChannel = "CloudWatch"
	NotificationChannelEventBridge NotificationChannel = "EventBridge"
	NotificationChannelHealth      NotificationChannel = "Health"
)

// Values returns all known values for NotificationChannel. Note that this can be
// expanded in the future, and so it is only as up to date as the client.
//
// The ordering of this slice is not guaranteed to be stable across updates.
func (NotificationChannel) Values() []NotificationChannel {
	return []NotificationChannel{
		"ALL",
		"CloudWatch",
		"EventBridge",
		"Health",
	}
}

type NotificationEvent string

// Enum values for NotificationEvent
const (
	NotificationEventCaCertificateExpiry        NotificationEvent = "CA_CERTIFICATE_EXPIRY"
	NotificationEventEndEntityCertificateExpiry NotificationEvent = "END_ENTITY_CERTIFICATE_EXPIRY"
)

// Values returns all known values for NotificationEvent. Note that this can be
// expanded in the future, and so it is only as up to date as the client.
//
// The ordering of this slice is not guaranteed to be stable across updates.
func (NotificationEvent) Values() []NotificationEvent {
	return []NotificationEvent{
		"CA_CERTIFICATE_EXPIRY",
		"END_ENTITY_CERTIFICATE_EXPIRY",
	}
}

type TrustAnchorType string

// Enum values for TrustAnchorType
const (
	TrustAnchorTypeAwsAcmPca         TrustAnchorType = "AWS_ACM_PCA"
	TrustAnchorTypeCertificateBundle TrustAnchorType = "CERTIFICATE_BUNDLE"
)
