// Code generated by smithy-go-codegen DO NOT EDIT.

package types

import (
	smithydocument "github.com/aws/smithy-go/document"
)

type AssumedRoleUser struct {
	Arn *string

	AssumedRoleId *string

	noSmithyDocumentSerde
}

type CredentialResponse struct {
	AssumedRoleUser *AssumedRoleUser

	Credentials *Credentials

	PackedPolicySize *int32

	RoleArn *string

	SourceIdentity *string

	noSmithyDocumentSerde
}

type Credentials struct {
	AccessKeyId *string

	Expiration *string

	SecretAccessKey *string

	SessionToken *string

	noSmithyDocumentSerde
}

type noSmithyDocumentSerde = smithydocument.NoSerde
